### ISSUE TITLE
React v0.13.x support?

### ISSUE THREAD

**Issue by cesarandreu** [yahoo/fluxible-immutable-utils#12]
Any plans for React v0.13.x support?

I tried updating fluxible and react, but it breaks ComponentMixin. I think It might be that jsx-test doesn't work with React v0.13.x. :(

**Comment by longlho** [comment]
any log would be great :)

**Comment by kaddopur** [comment]
```console
$ npm i --save fluxible-immutable-utils
npm WARN package.json fluxible-plugin-routr@0.3.0 No repository field.
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer flux-router-component@0.6.1 wants react@0.13.x
npm ERR! peerinvalid Peer fluxible@0.4.3 wants react@0.13.x
npm ERR! peerinvalid Peer fluxible-immutable-utils@0.1.3 wants react@^0.12.0
```

Please bump react version in peerDependencies to `^0.13.0`.
In fact React is only used at one place
https://github.com/yahoo/fluxible-immutable-utils/blob/master/src/ComponentMixin.js#L26

**Comment by cesarandreu** [comment]
Ah, sorry for the slow reply.

```sh
~/D/fluxible-immutable-utils git:master ❯❯❯ mocha tests/unit/ --recursive --reporter spec                             ✱


  ImmutableMixin component functions
    #objectsToIgnore
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      1) should bypass certain props fields if are ignored
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      2) should warn certain if next state is mutable
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      3) should bypass certain state fields if are ignored
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      4) should merge w/ default certain state fields if are ignored
    #componentWillMount
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      5) should raise warnings if non immutable props are passed
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      6) should not raise warnings for children
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      7) does not raise warning if props or state is null
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      8) should raise warkings if there are non immutable states
    #getStateOnChange
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      9) should merge the getInitialState with getStateOnChange
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      10) should call getStateOnChange to initialize state
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      11) shouldn't crash if getStateOnChange is not there
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      12) should pass onChange arguments to getStateOnChange
    #shouldComponentUpdate
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
      13) "before each" hook

  createImmutableStore
    #initialize
      ✓ defines a immutable _state
    #rehydrate
      ✓ sets the state
    #dehydrate
      ✓ gets the initial state
      ✓ gets the rehydrated state
    #setState
      ✓ updates the state and emits a "change" event
      ✓ updates the state and emit a custom event
      ✓ updates the state and passes a custom payload
      ✓ only emits the chage if there are changes
    #mergeState
      ✓ replaces the list with a new list
      ✓ merges the state and emits a "change" event
      ✓ merges the state and emit a custom event
      ✓ merges the state and passes a custom payload
      ✓ only emits the change if there the stateFragment is different


  13 passing (49ms)
  13 failing

  1) ImmutableMixin component functions #objectsToIgnore should bypass certain props fields if are ignored:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:36:17)

  2) ImmutableMixin component functions #objectsToIgnore should warn certain if next state is mutable:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:49:28)

  3) ImmutableMixin component functions #objectsToIgnore should bypass certain state fields if are ignored:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:72:28)

  4) ImmutableMixin component functions #objectsToIgnore should merge w/ default certain state fields if are ignored:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:93:28)

  5) ImmutableMixin component functions #componentWillMount should raise warnings if non immutable props are passed:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:119:17)

  6) ImmutableMixin component functions #componentWillMount should not raise warnings for children:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:134:17)

  7) ImmutableMixin component functions #componentWillMount does not raise warning if props or state is null:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:153:17)

  8) ImmutableMixin component functions #componentWillMount should raise warkings if there are non immutable states:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:169:17)

  9) ImmutableMixin component functions #getStateOnChange should merge the getInitialState with getStateOnChange:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:191:33)

  10) ImmutableMixin component functions #getStateOnChange should call getStateOnChange to initialize state:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:211:17)

  11) ImmutableMixin component functions #getStateOnChange shouldn't crash if getStateOnChange is not there:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:221:33)

  12) ImmutableMixin component functions #getStateOnChange should pass onChange arguments to getStateOnChange:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:238:33)

  13) ImmutableMixin component functions #shouldComponentUpdate "before each" hook:
     TypeError: Cannot read property '__reactAutoBindMap' of null
      at Context.<anonymous> (tests/unit/ComponentMixin.js:263:29)
```

This is after updating fluxible to v0.4.0, react to v0.13.0, and updating createStore in createImmutableStore.js to require `fluxible/addons/createStore`.

**Comment by 3den** [comment]
For react v0.13.0 we should release a higher order component instead of a mixing.

**Comment by 3den** [comment]
* Mixins are deprecated

**Comment by cesarandreu** [comment]
I'm most interested in `createImmutableStore` :D.

**Comment by 3den** [comment]
@cesarandreu I plan to add something like a `createImmutableComponent(YourComponent)`
